services:
  database:
    image: postgres:16
    container_name: smallcompany-db
    environment:
      POSTGRES_DB: smallcompany
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: smallcompany-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/smallcompany
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      JWT_SECRET: this-is-demo-secret-key-change-later
      AES_SECRET_KEY: 12345678901234567890123456789012
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    container_name: smallcompany-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    depends_on:
      - backend

volumes:
  postgres_data: