-- Demo data for this project is seeded by Spring Boot at startup so that:
-- 1. Passwords are hashed with BCryptPasswordEncoder inside Java.
-- 2. Sensitive fields are encrypted with AES-GCM using the runtime ENCRYPTION_KEY.
-- 3. Sample enrollments/certificates stay aligned with the current entity model.
--
-- Suggested local reset order:
-- DELETE FROM refresh_tokens;
-- DELETE FROM password_reset_tokens;
-- DELETE FROM certificates;
-- DELETE FROM enrollments;
-- DELETE FROM lessons;
-- DELETE FROM courses;
-- DELETE FROM audit_logs;
-- DELETE FROM users;

