spring.application.name=securityapp
spring.profiles.active=dev

server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

app.jwt.secret=change-this-secret-key-to-a-long-random-value-before-deploy
app.jwt.expiration-ms=86400000
app.aes.secret=change-this-32-char-aes-secret-key
